CREATE TABLE DADOSPACIENTE (
	MATRICULA INT,
	NOME VARCHAR(80),
    NASCIMENTO VARCHAR(15),
    SEXO VARCHAR(10),
    CONVENIO VARCHAR(10),
    RG VARCHAR(15),
	CPF VARCHAR(15),
    EMAIL VARCHAR(80),
    ENDERECO VARCHAR(50),
    BAIRRO VARCHAR(50),
    MUNICIPIO VARCHAR(40),
    UF CHAR(2)NULL,
    CEP VARCHAR(10)NULL,
    CELULAR VARCHAR(20)NULL,
CONSTRAINT PK_MATRICULA PRIMARY KEY (MATRICULA),
CONSTRAINT UQ_DADOSPACIENTE_CPF UNIQUE (CPF),
CONSTRAINT UQ_DADOSPACIENTE_RG UNIQUE (RG)
);

CREATE TABLE DADOSFUNCIONARIO (
	IDFUNCIONARIO INT NOT NULL,
    CRO INT ,
    CATEGORIA VARCHAR(20) NOT NULL,
	NOME VARCHAR(80) NOT NULL,
    NASCIMENTO VARCHAR(15) NOT NULL,
    SEXO VARCHAR(10) NOT NULL,    
    RG VARCHAR(15) NOT NULL,
	CPF VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    ENDERECO VARCHAR(50) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    MUNICIPIO VARCHAR(40) NOT NULL,
    UF CHAR(2) NOT NULL,
    CEP VARCHAR(10) NOT NULL,
    CELULAR VARCHAR(20) NOT NULL,
CONSTRAINT PK_IDFUNCIONARIO PRIMARY KEY (IDFUNCIONARIO),
CONSTRAINT UQ_DADOSFUNCIONARIO_CRO UNIQUE (CRO),
CONSTRAINT UQ_DADOSFUNCIONARIO_RG UNIQUE (RG),
CONSTRAINT UQ_DADOSFUNCIONARIO_CPF UNIQUE (CPF)
);

CREATE TABLE AGENDA (	
	IDAGENDA INT NOT NULL,
    MATRICULA INT NOT NULL,
    IDFUNCIONARIO INT NOT NULL,
	DATAAGENDA DATE NOT NULL,
	HORAAGENDA INT NOT NULL,
CONSTRAINT PK_IDAGENDA PRIMARY KEY (IDAGENDA),
CONSTRAINT FK_AGENDA_DADOSPACIENTE FOREIGN KEY (MATRICULA) REFERENCES DADOSPACIENTE (MATRICULA),
CONSTRAINT FK_AGENDA_DADOSFUNCIONARIO FOREIGN KEY (IDFUNCIONARIO) REFERENCES DADOSFUNCIONARIO (CRO)
);

CREATE TABLE RECEITA(
	MATRICULA INT,
	MEDICAMENTO VARCHAR(15),
    QUANTIDADE VARCHAR(20),
    PRESCRICAO VARCHAR(10),
CONSTRAINT FK_RECEITA_DADOSPACIENTE FOREIGN KEY (MATRICULA) REFERENCES DADOSPACIENTE (MATRICULA)
);